### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Creeeamy** [PogProgramming/TowerDefense#1]
-Tower upgrades don't check to see if you have enough money, making it possible to infinitely upgrade.

-You can upgrade a troop so far it begins to do negative damage, and heal enemies.

**Comment by PogProgramming** [comment]
Both bugs have been fixed in commit [#f37dbfc](https://github.com/PogProgramming/TowerDefense/commit/f37dbfcd6de5c0fbda13faa42e5b62e96cb2ad08), thanks for letting me know! If you find any more, don't hesitate to alert me.

Edit: updated hyperlink
