### ISSUE TITLE
Possible to upgrade into negative stats

### ISSUE THREAD

**Issue by Creeeamy** [PogProgramming/TowerDefense#2]
**System**: All

**Bug**: You can upgrade troops so far they can gain negative damage and increase enemies health when they fire

**Steps to Recreate**: Simply upgrade the same troop repeatedly until their damage turns negative

**Severity**: Normal

**Comment by PogProgramming** [comment]
Hi there, I haven't been able to reproduce this error. Have you updated pulled the latest commits?
