### ISSUE TITLE
Can place Enemies off map

### ISSUE THREAD

**Issue by Creeeamy** [PogProgramming/TowerDefense#3]
**System**: All

**Bug**: Can place enemies off the grid at any point

**Steps to recreate**: Purchase a troop and place them off the map

**Severity**: Minor

**Comment by PogProgramming** [comment]
Hi there, this has already been patched in commit [#947d89f](https://github.com/PogProgramming/TowerDefense/commit/ca4d0ad3e48c44fe9274991ef2ba8b36038ca153).
